# Generated by Django 3.1.4 on 2021-02-06 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notes', '0001_initial'),
        ('DefinitionsAndExplanations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('copied_notes', models.ManyToManyField(blank=True, related_name='Notes', to='Notes.Notes')),
                ('saved_definitions', models.ManyToManyField(blank=True, related_name='Definitions', to='DefinitionsAndExplanations.Definition')),
                ('saved_explanations', models.ManyToManyField(blank=True, related_name='Explanations', to='DefinitionsAndExplanations.Explanation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
