# Generated by Django 3.1.4 on 2021-02-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefinitionsAndExplanations', '0003_videos'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_videos',
            field=models.ManyToManyField(blank=True, related_name='Videos', to='DefinitionsAndExplanations.Videos'),
        ),
    ]
