# Generated by Django 3.1.4 on 2021-02-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20210208_1516'),
        ('DefinitionsAndExplanations', '0002_explanationlinks_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('links', models.CharField(max_length=100)),
                ('topic', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.topic')),
            ],
        ),
    ]
