# Generated by Django 3.1.4 on 2021-02-06 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210207_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
    ]
