# Generated by Django 3.1.4 on 2021-02-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20210207_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='topic',
        ),
        migrations.AddField(
            model_name='concept',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='Topic', to='Home.Topic'),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='Subject', to='Home.Subject'),
        ),
        migrations.RemoveField(
            model_name='topic',
            name='grade',
        ),
        migrations.AddField(
            model_name='topic',
            name='grade',
            field=models.ManyToManyField(blank=True, related_name='Grade', to='Home.Grade'),
        ),
    ]
